// This file is auto-generated by @hey-api/openapi-ts

export type GetHelloWorldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetHelloWorldResponses = {
    /**
     * Hello, World!
     */
    200: string;
};

export type GetHelloWorldResponse = GetHelloWorldResponses[keyof GetHelloWorldResponses];

export type ClientOptions = {
    baseUrl: string;
};