// This file is auto-generated by @hey-api/openapi-ts

export type ControllerCreateUserBody = {
    email: string;
    name: string;
};

export type GormDeletedAt = {
    time?: string;
    /**
     * Valid is true if Time is not NULL
     */
    valid?: boolean;
};

export type ModelsUser = {
    createdAt?: string;
    deletedAt?: GormDeletedAt;
    email?: string;
    id?: number;
    name?: string;
    updatedAt?: string;
};

export type CreateUserData = {
    /**
     * User data
     */
    body: ControllerCreateUserBody;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Error creating user
     */
    500: string;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * User created successfully
     */
    200: ModelsUser;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ClientOptions = {
    baseUrl: string;
};