// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zGetHelloWorldData = z.object({
    body: z.never().optional(),
    headers: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Hello, World!
 */
export const zGetHelloWorldResponse = z.string();