// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zControllerCreateUserBody = z.object({
    email: z.string().email(),
    name: z.string()
});

export const zGormDeletedAt = z.object({
    time: z.string().optional(),
    valid: z.boolean().optional()
});

export const zModelsUser = z.object({
    createdAt: z.string().optional(),
    deletedAt: zGormDeletedAt.optional(),
    email: z.string().optional(),
    id: z.number().int().optional(),
    name: z.string().optional(),
    updatedAt: z.string().optional()
});

export const zCreateUserData = z.object({
    body: zControllerCreateUserBody,
    headers: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User created successfully
 */
export const zCreateUserResponse = zModelsUser;