info:
  contact: {}
  title: Freelancer Toolkit API
  version: 0.0.1
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
swagger: "2.0"
